#include QMK_KEYBOARD_H
#include "keymap_steno.h"

#define _DVORAK0 0
#define _QWERTY1 1
#define _MIRROR2 2
#define _QMIRROR3 3
#define _NORMMODS4 4
#define _NUMARROW5 5
#define _RARROW6 6
#define _SYMBOL7 7
#define _MOUSE8 8
#define _LMOUSE9 9
#define _MEDIA10 10
#define _PLOVER11 11
#define _SETTING12 12
#define RGBLIGHT_EFFECT_STATIC_GRADIENT

enum custom_keycodes {
    DVORAK0 = SAFE_RANGE,
    QWERTY1,
    MIRROR2,
    QMIRROR3,
    NORMMODS4,
    NUMARROW5,
    RARROW6,
	SYMBOL7,
	MOUSE8,
	LMOUSE9,
	MEDIA10,
	PLOVER11,
	SETTING12
};

void matrix_init_user() {
  steno_set_mode(STENO_MODE_GEMINI); // or STENO_MODE_BOLT
}

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_DVORAK0] = LAYOUT_ortho_5x15(
KC_ESC,           KC_1,            KC_2,            KC_3,   KC_4,   KC_5,   TO(0),   KC_F13,  KC_SLEP, KC_6,  	KC_7,    KC_8,    KC_9,            KC_0,   KC_DEL,  		 \
KC_TAB,           KC_QUOT,         KC_COMM,         KC_DOT, KC_P,   KC_Y,   KC_HOME, KC_BSLS, KC_PGUP, KC_F,  	KC_G,    KC_C,    KC_R,            KC_L,   KC_SLSH, 		 \
KC_MINS,          KC_A,            KC_O,            KC_E,   KC_U,   KC_I,   KC_END,  KC_UP,   KC_PGDN, KC_D,  	KC_H,    KC_T,    KC_N,            KC_S,   KC_ENT,  		 \
KC_LSPO,          KC_SCLN,         KC_Q,            KC_J,   KC_K,   KC_X,   KC_LEFT, KC_DOWN, KC_RGHT, KC_B,  	KC_M,    KC_W,    KC_V,            KC_Z,   KC_RSPC, 		 \
LM(1, MOD_LCTL),  LM(1, MOD_LGUI), LM(1, MOD_LALT), KC_NO,  KC_SPC, KC_NO,  MO(2),   MO(10),  MO(7),   KC_TRNS, KC_BSPC, KC_TRNS, LM(1, MOD_RALT), KC_APP, LM(1, MOD_RCTL)  \
),

[_QWERTY1] = LAYOUT_ortho_5x15(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_TRNS, KC_TRNS, KC_TRNS, KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_QUOT, \
KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_TRNS, KC_TRNS, KC_TRNS, KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_TRNS, \
KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_TRNS, KC_TRNS, KC_TRNS, KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, \
KC_LCTL, KC_LGUI, KC_LALT, KC_TRNS, KC_TRNS, KC_TRNS, MO(3),   MO(10),  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RALT, KC_TRNS, KC_RCTL  \
),

[_MIRROR2] = LAYOUT_ortho_5x15(
KC_DEL,  KC_0,    KC_9,    KC_8,    KC_7,    KC_6,    TO(0),   MO(12),  KC_TRNS, KC_TRNS, KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, KC_TRNS, \
KC_SLSH, KC_L,    KC_R,    KC_C,    KC_G,    KC_F,    KC_TRNS, TG(9),   KC_TRNS, KC_TRNS, KC_P7,   KC_P8,   KC_P9,   KC_PPLS, KC_TRNS, \
KC_ENT,  KC_S,    KC_N,    KC_T,    KC_H,    KC_D,    KC_BSPC, KC_BTN3, KC_BSPC, KC_TRNS, KC_P4,   KC_P5,   KC_P6,   KC_PPLS, KC_TRNS, \
KC_RSPC, KC_Z,    KC_V,    KC_W,    KC_M,    KC_B,    KC_BTN1, KC_BTN2, KC_TRNS, KC_TRNS, KC_P1,   KC_P2,   KC_P3,   KC_PENT, KC_TRNS, \
KC_TRNS, KC_APP,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TG(4),   TG(8),   KC_TRNS, KC_P0,   KC_TRNS, KC_PDOT, KC_TRNS, KC_TRNS  \
),

[_QMIRROR3] = LAYOUT_ortho_5x15(
KC_DEL,  KC_0,    KC_9,    KC_8,    KC_7,    KC_6,    TO(0),   MO(12),  KC_TRNS, KC_TRNS, KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, KC_TRNS, \
KC_QUOT, KC_P,    KC_O,    KC_I,    KC_U,    KC_Y,    KC_TRNS, TG(9),   KC_TRNS, KC_TRNS, KC_P7,   KC_P8,   KC_P9,   KC_PPLS, KC_TRNS, \
KC_ENT,  KC_SCLN, KC_L,    KC_K,    KC_J,    KC_H,    KC_BSPC, KC_BTN3, KC_TRNS, KC_TRNS, KC_P4,   KC_P5,   KC_P6,   KC_PPLS, KC_TRNS, \
KC_RSFT, KC_SLSH, KC_DOT,  KC_COMM, KC_M,    KC_N,    KC_BTN1, KC_BTN2, KC_TRNS, KC_TRNS, KC_P1,   KC_P2,   KC_P3,   KC_PENT, KC_TRNS, \
KC_RCTL, KC_APP,  KC_RALT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TG(4),   TG(8),   KC_TRNS, KC_P0,   KC_TRNS, KC_PDOT, KC_TRNS, KC_TRNS  \
),

[_NORMMODS4] = LAYOUT_ortho_5x15(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_LSFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RSFT, \
KC_LCTL, KC_LGUI, KC_LALT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RALT, KC_TRNS, KC_RCTL  \
),

[_NUMARROW5] = LAYOUT_ortho_5x15(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0),   KC_TRNS, KC_TRNS, KC_TRNS, KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_UP,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P7,   KC_P8,   KC_P9,   KC_PPLS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, KC_TRNS, KC_P4,   KC_P5,   KC_P6,   KC_PPLS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P1,   KC_P2,   KC_P3,   KC_PENT, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P0,   KC_TRNS, KC_PDOT, KC_TRNS, KC_TRNS  \
),

[_RARROW6] = LAYOUT_ortho_5x15(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP,   KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS  \
),

[_SYMBOL7] = LAYOUT_ortho_5x15(
KC_TRNS, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   TO(0),   KC_TRNS,  KC_TRNS, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  \
KC_TILD, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC, RGB_TOG, RGB_RMOD, RGB_MOD, KC_CIRC, KC_AMPR, KC_ASTR, KC_MINS, KC_PLUS, KC_F12,  \
KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    RGB_HUI, RGB_SAI,  RGB_VAI, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_EQL,  \
KC_LCPO, KC_PSCR, KC_SLCK, KC_LBRC, KC_LCBR, KC_LPRN, RGB_HUD, RGB_SAD,  RGB_VAD, KC_RPRN, KC_RCBR, KC_RBRC, KC_PAUS, KC_INS,  KC_RCPC, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TG(5),   TG(6),    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS  \
),

[_MOUSE8] = LAYOUT_ortho_5x15(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_U, KC_MS_U, KC_WH_D, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_ACL2, KC_BTN2, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN4, KC_BTN3, KC_BTN5, KC_ACL1, KC_BTN1, \
KC_TRNS, KC_ACL1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TG(8),   KC_TRNS, KC_BTN1, KC_TRNS, KC_TRNS, KC_TRNS, KC_ACL0  \
),

[_LMOUSE9] = LAYOUT_ortho_5x15(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_WH_D, KC_MS_U, KC_WH_U, KC_TRNS, KC_TRNS, TG(9),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_BTN2, KC_ACL2, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_BTN1, KC_ACL1, KC_BTN4, KC_BTN3, KC_BTN5, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS  \
),

[_MEDIA10] = LAYOUT_ortho_5x15(
TG(1),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(1),   TG(1),   TG(11),  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, \
KC_TRNS, KC_TRNS, KC_WH_D, KC_MS_U, KC_WH_U, KC_TRNS, KC_MUTE, KC_VOLD, KC_VOLU, KC_TRNS, KC_WH_U, KC_MS_U, KC_WH_D, KC_TRNS, KC_TRNS, \
KC_BTN2, KC_ACL2, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS, KC_MPRV, KC_MPLY, KC_MNXT, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_ACL2, KC_BTN2, \
KC_BTN1, KC_ACL1, KC_BTN4, KC_BTN3, KC_BTN5, KC_TRNS, KC_CALC, KC_MSEL, KC_MYCM, KC_TRNS, KC_BTN4, KC_BTN3, KC_BTN5, KC_ACL1, KC_BTN1, \
KC_ACL1, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_TRNS, KC_TRNS, KC_TRNS, KC_ACL1  \
),

[_PLOVER11] = LAYOUT_ortho_5x15(
STN_N1,  STN_N2,  STN_N3,  STN_N4,  STN_N5,  STN_N6,  TO(0),   KC_TRNS, KC_NO,   STN_N7,  STN_N8,  STN_N9,  STN_NA,  STN_NB,  STN_NC, \
STN_FN,  STN_S1,  STN_TL,  STN_PL,  STN_HL,  STN_ST1, KC_NO,   KC_NO,   KC_NO,   STN_ST3, STN_FR,  STN_PR,  STN_LR,  STN_TR,  STN_DR, \
KC_NO,   STN_S2,  STN_KL,  STN_WL,  STN_RL,  STN_ST2, KC_NO,   TG(11),  KC_NO,   STN_ST4, STN_RR,  STN_BR,  STN_GR,  STN_SR,  STN_ZR, \
KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  \
KC_NO,   KC_NO,   KC_NO,   KC_NO,   STN_A,   KC_NO,   STN_O,   TG(11),  STN_E,   KC_NO,   STN_U,   KC_NO,   STN_PWR, STN_RE1, STN_RE2 \
),

[_SETTING12] = LAYOUT_ortho_5x15(
RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, NK_ON,   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, NK_OFF,  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO  \
)

};

const key_override_t numpad0_override = ko_make_basic(MOD_MASK_SHIFT, KC_P0, KC_LCBR);
const key_override_t numpad1_override = ko_make_basic(MOD_MASK_SHIFT, KC_P1, KC_EXLM);
const key_override_t numpad2_override = ko_make_basic(MOD_MASK_SHIFT, KC_P2, KC_AT);
const key_override_t numpad3_override = ko_make_basic(MOD_MASK_SHIFT, KC_P3, KC_HASH);
const key_override_t numpad4_override = ko_make_basic(MOD_MASK_SHIFT, KC_P4, KC_DLR);
const key_override_t numpad5_override = ko_make_basic(MOD_MASK_SHIFT, KC_P5, KC_PERC);
const key_override_t numpad6_override = ko_make_basic(MOD_MASK_SHIFT, KC_P6, KC_CIRC);
const key_override_t numpad7_override = ko_make_basic(MOD_MASK_SHIFT, KC_P7, KC_AMPR);
const key_override_t numpad8_override = ko_make_basic(MOD_MASK_SHIFT, KC_P8, KC_ASTR);
const key_override_t numpad9_override = ko_make_basic(MOD_MASK_SHIFT, KC_P9, KC_RCBR);
const key_override_t numpad_min_override = ko_make_basic(MOD_MASK_SHIFT, KC_PMNS, KC_UNDS);
const key_override_t numpad_plus_override = ko_make_basic(MOD_MASK_SHIFT, KC_PMNS, KC_EQL);

// This globally defines all key overrides to be used
const key_override_t **key_overrides = (const key_override_t *[]){
    &numpad0_override,
    &numpad1_override,
    &numpad2_override,
    &numpad3_override,
    &numpad4_override,
    &numpad5_override,
    &numpad6_override,
    &numpad7_override,
    &numpad8_override,
    &numpad9_override,
    &numpad_min_override,
    &numpad_plus_override,
    NULL
};

#define MAGIC_BOOT 0x544F4F42UL
#define MAGIC_REG *(volatile uint32_t*)0x20004000
void bootloader_jump(void) {
    MAGIC_REG = MAGIC_BOOT;
    NVIC_SystemReset();
};